spring:
  application:
    name: WebShop

  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/WebShop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
=======
    url: jdbc:mysql://mysql:3306/WebShop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
>>>>>>> 5e94152 (tanh fix docker)
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
<<<<<<< HEAD
=======
      idle-timeout: 600000
      max-lifetime: 1800000
>>>>>>> 5e94152 (tanh fix docker)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: 12345678
  bucket: product-images
<<<<<<< HEAD
=======

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  address: 0.0.0.0
  port: 8080

>>>>>>> 5e94152 (tanh fix docker)
